### ISSUE TITLE
Adição dos icones  "langs"

### ISSUE THREAD

**Issue by YannDarkz** [Sync-BR/perfil#1]
Fica de preferencia do Owner a atualização do read.me. Visando em aprimorar a interface cada vez mais amigável e intuitiva com os seus ideais.

**Comment by Sync-BR** [comment]
> Fica de preferencia do Owner a atualização do read.me. Visando em aprimorar a interface cada vez mais amigável e intuitiva com os seus ideais.

Agradeço o freedback. Lançarei uma nova atualização em breve!
